baseURL = "https://dev.trueboss.com.ph/"
languageCode = "en-us"
title = "TRUE BOSS"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Order"
url     = "order"
weight  = 2
[[menu.main]]
name    = "About Us"
url     = "about"
weight  = 3
[[menu.main]]
name    = "FAQs"
url     = "faqs"
weight  = 4
#[[menu.main]]
#name    = "Blog"
#url     = "blog"
#weight  = 5
#[[menu.main]]
#name    = "Contact"
#url     = "contact"
#weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Trueboss Philippines"
author = "Calvin Enriquez"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/True_Boss6.jpg"
#heading = "HI, Welcome to Trueboss!"
#description = "We offer fruit enzyme based drinks for anyone aged 1 to 100 that make your body glow inside out! Visit Us! True Boss E. Rod True Boss MOA True Boss West Ave"
# button
btn     = true
btnText = "Order Now!"
btnURL  = "/order"

# flip text
[[params.banner.flipText]]
title   = "ENZYME"
[[params.banner.flipText]]
title   = "MILK"
[[params.banner.flipText]]
title   = "TEA"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/truebossph/"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/truebossph"